# Generated by Django 4.2 on 2026-01-07 23:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(help_text='RUT sin puntos, con guión (ej: 12345678-9)', max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('numero_tarjeta_bip', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=20)),
                ('email_verificado', models.BooleanField(default=False)),
                ('telefono_verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EspacioEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField(help_text='Número de fila (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('columna', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Columna A, B o C', max_length=1)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espacio de Estacionamiento',
                'verbose_name_plural': 'Espacios de Estacionamiento',
                'db_table': 'espacios_estacionamiento',
                'ordering': ['estacion', 'fila', 'columna'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('linea', models.CharField(choices=[('L1', 'Línea 1'), ('L2', 'Línea 2'), ('L3', 'Línea 3'), ('L4', 'Línea 4'), ('L4A', 'Línea 4A'), ('L5', 'Línea 5'), ('L6', 'Línea 6'), ('L7', 'Línea 7')], default='L1', max_length=3)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('espacios_totales', models.IntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'db_table': 'estaciones',
                'ordering': ['linea', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=15)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion_reserva', models.DateTimeField()),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('qr_entrada', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('qr_salida', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('horas_gratis', models.IntegerField(default=2)),
                ('costo_hora_extra', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('pasaje_usado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='api.espacioestacionamiento')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.estacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PROBLEMA_TECNICO', 'Problema Técnico'), ('PROBLEMA_PAGO', 'Problema de Pago'), ('PROBLEMA_QR', 'Problema con QR'), ('CONSULTA', 'Consulta General'), ('SUGERENCIA', 'Sugerencia'), ('OTRO', 'Otro')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'tickets_soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('calificacion_seguridad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calificacion_limpieza', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calificacion_accesibilidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.estacion')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='api.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'resenas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TARJETA_BIP', 'Tarjeta Bip!'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15)),
                ('transaccion_id', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='api.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RESERVA_CONFIRMADA', 'Reserva Confirmada'), ('RESERVA_PROXIMA_EXPIRACION', 'Reserva Próxima a Expirar'), ('RESERVA_EXPIRADA', 'Reserva Expirada'), ('PAGO_REQUERIDO', 'Pago Requerido'), ('PAGO_EXITOSO', 'Pago Exitoso'), ('RECORDATORIO', 'Recordatorio'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['linea', 'estado'], name='estaciones_linea_2d9212_idx'),
        ),
        migrations.AddField(
            model_name='espacioestacionamiento',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='api.estacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario', 'estado'], name='reservas_usuario_2844a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estacion', 'estado'], name='reservas_estacio_9d893d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['qr_entrada'], name='reservas_qr_entr_7aa977_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['qr_salida'], name='reservas_qr_sali_04b168_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('usuario', 'reserva')},
        ),
        migrations.AddIndex(
            model_name='espacioestacionamiento',
            index=models.Index(fields=['estacion', 'estado'], name='espacios_es_estacio_42ef72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='espacioestacionamiento',
            unique_together={('estacion', 'fila', 'columna')},
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rut'], name='usuarios_rut_5379eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='usuarios_usernam_7abab6_idx'),
        ),
    ]
